### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Dumeowmeow** [chenyangzhu1/MultiBooth#1]
At the position of the red arrow, S* has become an embedding, do we need to enter the CLIP text encoder again for encoding?
![5H``K)$YV}U@_(`)X@~CM43](https://github.com/chenyangzhu1/MultiBooth/assets/99797884/94eace50-cddd-43d8-b65c-9469df6e24dc)

**Comment by chenyangzhu1** [comment]
Yes.
As indicated in the paper, S* functions as a placeholder string, and it is utilized in combination with other words to create a prompt (e.g., “a photo of a S* dog”) before being sent into the text encoder.
